#!/bin/bash
#
# Generated by yaygg at [2018-05-06 13:14].
#
Rescue_Applications() {
  local handle="$1"
  local tabnum="$2"
  yad --plug="$handle" --tabnum="$tabnum" --form \
      --title="$FUNCNAME" \
      --columns=3 \
      --field='Antergos  Rescue  Wiki  Online!'"/usr/share/icons/rescue/ar-wiki.svg"'!'"Open Antergos Rescue Wiki inside Browser":fbtn    'sh /home/rescue/.local/bin/a-r-wiki.sh' \
      --field='Antergos  Rescue  Wiki Offline!'"/usr/share/icons/rescue/help-browser.svg"'!'"Read Antergos Rescue WIKI offline as PDF book":fbtn    'sh /home/rescue/.local/bin/a-r-wiki-offline.sh' \
      --field='Antergos   Main   Wiki  Online!'"/usr/share/icons/rescue/distributor-logo-antergos.svg"'!'"Antergos Wiki open inside Browser":fbtn    'sh /home/rescue/.local/bin/a-wiki.sh' \
      --field='System   Journal  Live  Output!'"/usr/share/icons/rescue/terminal.svg"'!'"Shows SYSTEMD journal live inside a terminal":fbtn    'exo-open --launch TerminalEmulator journalctl -f' \
      --field='Clonezilla clone disk/partition!'"/usr/share/icons/rescue/clonezilla.svg"'!'"Clonezilla is a partition and disk imaging/cloning program":fbtn    'exo-open --launch TerminalEmulator sudo clonezilla' \
      --field='DDRescue Data Recovery Tool!'"/usr/share/icons/rescue/ddrescue.svg"'!'"GNU ddrescue is a data recovery tool. It copies data from one file or block device (hard disc, cdrom, etc) to another, trying to rescue the good parts first in case of read errors.":fbtn    'exo-open --launch TerminalEmulator man ddrescue' \
      --field='Show System   Hardware  Information!'"/usr/share/icons/rescue/hardinfo.svg"'!'"Open editor with all hardware you have installed, uses inxi and hw-info":fbtn    'sh /home/rescue/hardware.sh' \
      --field='Glances Advanced System Monitoring!'"/usr/share/icons/rescue/terminal.svg"'!'"Glances is an advanced system monitoring tool":fbtn    'exo-open --launch TerminalEmulator glances --percpu' \
      --field='TestDisk free data recovery software!'"/usr/share/icons/rescue/terminal.svg"'!'"TestDisk is powerful free data recovery software! It was primarily designed to help recover lost partitions and/or make non-booting disks bootable again when these symptoms are caused by faulty software":fbtn    'exo-open --launch TerminalEmulator sudo testdisk' \
      &> /dev/null &
}

PrepareTabs() {
  local handle="$1"
  local xx ix
  ix=1
  for xx in Rescue_Applications ; do
    $xx "$handle" "$((ix++))"
  done
}

StartHere() {
  local handle="987$$"
  PrepareTabs "$handle" || return $?
  yad --notebook --key=$handle --posx=80 --posy=80 --on-top \
      --title="Antergos-Rescue-Launcher" \
      --tab="Rescue Applications" \
      --button=gtk-quit:0
}

StartHere
